//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrustCalculator
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvestmentDetail
    {
        public Nullable<int> InvestmentID { get; set; }
        public Nullable<decimal> InvestmentValue { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public int ID { get; set; }
        public Nullable<int> TrustID { get; set; }
        public string Comment { get; set; }
        public string ExcessShortfall { get; set; }
        public Nullable<decimal> Maximum { get; set; }
        public Nullable<decimal> Minimum { get; set; }
    }
}
