//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrustCalculator
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TrustCalculatorEntities : DbContext
    {
        public TrustCalculatorEntities()
            : base("name=TrustCalculatorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CategoryDetail> CategoryDetails { get; set; }
        public DbSet<InvestmentDetail> InvestmentDetails { get; set; }
        public DbSet<ms_CategoryDetail> ms_CategoryDetail { get; set; }
        public DbSet<ms_InvestmentOption> ms_InvestmentOption { get; set; }
        public DbSet<TrustDetail> TrustDetails { get; set; }
        public DbSet<UserDetail> UserDetails { get; set; }
    }
}
