//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrustCalculator
{
    using System;
    using System.Collections.Generic;
    
    public partial class ms_InvestmentOption
    {
        public int InvestmentID { get; set; }
        public string InvestmentName { get; set; }
        public Nullable<double> Maximum { get; set; }
        public Nullable<double> Minimum { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
    }
}
