//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrustCalculator
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrustDetail
    {
        public string TrustName { get; set; }
        public int TrustID { get; set; }
        public string Address { get; set; }
        public string ContPerson { get; set; }
        public string PhoneNo { get; set; }
        public string PanNo { get; set; }
        public Nullable<decimal> Advances { get; set; }
        public Nullable<decimal> Total_Corps { get; set; }
    }
}
